#! /usr/bin/env python3

import argparse
import sys

from indy_node.utils.node_control_tool import NodeControlTool, daemonize


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Indy Node control tool - provides health check and restart commands')
    parser.add_argument(
        '--daemon', action='store_true',
        help='Fork and detach (for use as background service in containers)')
    args = parser.parse_args()

    try:
        from indy_common.config_util import getConfig
        config = getConfig()
    except Exception:
        config = None

    if args.daemon:
        daemonize()

    tool = NodeControlTool(config=config)
    tool.start()
